I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/conclusion.rpy", line 128, in script
    sound "audio/door.mp3"
Exception: Sayer 'sound' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/conclusion.rpy", line 128, in script
    sound "audio/door.mp3"
  File "C:\Users\Quirk\Documents\RenPy-Competition\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Quirk\Documents\RenPy-Competition\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'sound' is not defined.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Us and Them 
Wed Mar 15 03:17:16 2023
